# Input Boolean - Helpers de Simulacao
# Projeto Guilas - Casa Le Parc
# Criado: 2026-01-24

# --- PORTAS/PORTOES ---
garagem_aberta:
  name: "Garagem Aberta"
  icon: mdi:garage

social_aberta:
  name: "Social Aberta"
  icon: mdi:gate

porta_aberta:
  name: "Porta Aberta"
  icon: mdi:door

servico_aberta:
  name: "Servico Aberta"
  icon: mdi:gate

lavanderia_porta:
  name: "Lavanderia Porta"
  icon: mdi:door

sala_f_porta:
  name: "Sala F Porta"
  icon: mdi:door

dispensa_porta:
  name: "Dispensa Porta"
  icon: mdi:door

cozinha_porta:
  name: "Cozinha Porta"
  icon: mdi:door

# --- PRESENCA ---
frente_presenca:
  name: "Frente Presenca"
  icon: mdi:motion-sensor

sala_presenca:
  name: "Sala Presenca"
  icon: mdi:motion-sensor

master_presenca:
  name: "Master Presenca"
  icon: mdi:motion-sensor

jp_presenca:
  name: "JP Presenca"
  icon: mdi:motion-sensor

# --- PESSOAS EM CASA ---
gui_em_casa:
  name: "Gui Em Casa"
  icon: mdi:account

jp_em_casa:
  name: "JP Em Casa"
  icon: mdi:account

ana_em_casa:
  name: "Ana Em Casa"
  icon: mdi:account

m_em_casa:
  name: "M Em Casa"
  icon: mdi:account

# --- DISPOSITIVOS ---
pendente_sala_ligado:
  name: "Pendente Sala Ligado"
  icon: mdi:ceiling-light

alexa_ativa:
  name: "Alexa Ativa"
  icon: mdi:amazon-alexa
